WonderTradeOTNames1:
	db "RED@@@@@" ; $00
	db "BLUE@@@@" ; $01
	db "GREEN@@@" ; $02
	db "YELLOW@@" ; $03
	db "ORANGE@@" ; $04
	db "GOLD@@@@" ; $05
	db "SILVER@@" ; $06
	db "CRYSTAL@" ; $07
	db "RUBY@@@@" ; $08
	db "SAFIRE@@" ; $09
	db "EMERALD@" ; $0A
	db "JADE@@@@" ; $0B
	db "DIAMOND@" ; $0C
	db "PEARL@@@" ; $0D
	db "PLATINA@" ; $0E
	db "HEART@@@" ; $0F
	db "SOUL@@@@" ; $10
	db "MIND@@@@" ; $11
	db "BLACK@@@" ; $12
	db "WHITE@@@" ; $13
	db "GRAY@@@@" ; $14
	db "X@@@@@@@" ; $15
	db "Y@@@@@@@" ; $16
	db "Z@@@@@@@" ; $17
	db "ALPHA@@@" ; $18
	db "OMEGA@@@" ; $19
	db "DELTA@@@" ; $1A
	db "LAMBDA@@" ; $1B
	db "THETA@@@" ; $1C
	db "ZETA@@@@" ; $1D
	db "SUN@@@@@" ; $1E
	db "MOON@@@@" ; $1F
	db "STAR@@@@" ; $20
	db "ASH@@@@@" ; $21
	db "GARY@@@@" ; $22
	db "LEAF@@@@" ; $23
	db "ETHAN@@@" ; $24
	db "LYRA@@@@" ; $25
	db "HIRO@@@@" ; $26
	db "KRIS@@@@" ; $27
	db "BRENDAN@" ; $28
	db "MAY@@@@@" ; $29
	db "WALLY@@@" ; $2A
	db "LUCAS@@@" ; $2B
	db "DAWN@@@@" ; $2C
	db "BARRY@@@" ; $2D
	db "HILBERT@" ; $2E
	db "HILDA@@@" ; $2F
	db "CHEREN@@" ; $30
	db "BIANCA@@" ; $31
	db "NATE@@@@" ; $32
	db "ROSA@@@@" ; $33
	db "HUGH@@@@" ; $34
	db "CALEM@@@" ; $35
	db "SERENA@@" ; $36
	db "SHAUNA@@" ; $37
	db "TREVOR@@" ; $38
	db "TIERNO@@" ; $39
	db "HAU@@@@@" ; $3A
	db "LILLIE@@" ; $3B
	db "GLADION@" ; $3C
	db "WES@@@@@" ; $3D
	db "MICHAEL@" ; $3E
	db "TODD@@@@" ; $3F
	db "OAK@@@@@" ; $40
	db "ELM@@@@@" ; $41
	db "IVY@@@@@" ; $42
	db "BIRCH@@@" ; $43
	db "ROWAN@@@" ; $44
	db "JUNIPER@" ; $45
	db "SYCAMOR@" ; $46
	db "KUKUI@@@" ; $47
	db "WILLOW@@" ; $48
	db "SAMUEL@@" ; $49
	db "SAMSON@@" ; $4A
	db "COZMO@@@" ; $4B
	db "FENNEL@@" ; $4C
	db "CEDRIC@@" ; $4D
	db "SILKTRE@" ; $4E
	db "BURNET@@" ; $4F
	db "MOHN@@@@" ; $50
	db "KRANE@@@" ; $51
	db "BILL@@@@" ; $52
	db "LANETTE@" ; $53
	db "BRIGETT@" ; $54
	db "CELIO@@@" ; $55
	db "BEBE@@@@" ; $56
	db "AMANITA@" ; $57
	db "CASSIUS@" ; $58
	db "MOLAYNE@" ; $59
	db "BROCK@@@" ; $5A
	db "MISTY@@@" ; $5B
	db "SURGE@@@" ; $5C
	db "ERIKA@@@" ; $5D
	db "JANINE@@" ; $5E
	db "SABRINA@" ; $5F
	db "BLAINE@@" ; $60
	db "GIOVANI@" ; $61
	db "LORELEI@" ; $62
	db "BRUNO@@@" ; $63
	db "AGATHA@@" ; $64
	db "LANCE@@@" ; $65
	db "CISSY@@@" ; $66
	db "DANNY@@@" ; $67
	db "RUDY@@@@" ; $68
	db "LUANA@@@" ; $69
	db "PRIMA@@@" ; $6A
	db "FALKNER@" ; $6B
	db "BUGSY@@@" ; $6C
	db "WHITNEY@" ; $6D
	db "MORTY@@@" ; $6E
	db "CHUCK@@@" ; $6F
	db "JASMINE@" ; $70
	db "PRYCE@@@" ; $71
	db "CLAIR@@@" ; $72
	db "WILL@@@@" ; $73
	db "KOGA@@@@" ; $74
	db "KAREN@@@" ; $75
	db "ROXANNE@" ; $76
	db "BRAWLY@@" ; $77
	db "WATTSON@" ; $78
	db "FLANERY@" ; $79
	db "NORMAN@@" ; $7A
	db "WINONA@@" ; $7B
	db "LIZA@@@@" ; $7C
	db "TATE@@@@" ; $7D
	db "WALLACE@" ; $7E
	db "JUAN@@@@" ; $7F
	db "SIDNEY@@" ; $80
	db "PHOEBE@@" ; $81
	db "GLACIA@@" ; $82
	db "DRAKE@@@" ; $83
	db "STEVEN@@" ; $84
	db "ROARK@@@" ; $85
	db "GARDEN@@" ; $86
	db "MAYLENE@" ; $87
	db "WAKE@@@@" ; $88
	db "FANTINA@" ; $89
	db "BYRON@@@" ; $8A
	db "CANDICE@" ; $8B
	db "VOLKNER@" ; $8C
	db "AARON@@@" ; $8D
	db "BERTHA@@" ; $8E
	db "FLINT@@@" ; $8F
	db "LUCIAN@@" ; $90
	db "CYNTHIA@" ; $91
	db "CILAN@@@" ; $92
	db "CHILI@@@" ; $93
	db "CRESS@@@" ; $94
	db "ROXIE@@@" ; $95
	db "LENORA@@" ; $96
	db "BURGH@@@" ; $97
	db "ELESA@@@" ; $98
	db "CLAY@@@@" ; $99
	db "SKYLA@@@" ; $9A
	db "BRYCEN@@" ; $9B
	db "DRAYDEN@" ; $9C
	db "IRIS@@@@" ; $9D
	db "MARLON@@" ; $9E
	db "SHANTAL@" ; $9F
	db "MARSHAL@" ; $A0
	db "GRIMSLY@" ; $A1
	db "CAITLIN@" ; $A2
	db "ALDER@@@" ; $A3
	db "VIOLA@@@" ; $A4
	db "GRANT@@@" ; $A5
	db "KORRINA@" ; $A6
	db "RAMOS@@@" ; $A7
	db "CLEMONT@" ; $A8
	db "VALERIE@" ; $A9
	db "OLYMPIA@" ; $AA
	db "WULFRIC@" ; $AB
	db "MALVA@@@" ; $AC
	db "SIEBOLD@" ; $AD
	db "WIKTROM@" ; $AE
	db "DRASNA@@" ; $AF
	db "DIANTHA@" ; $B0
	db "ILIMA@@@" ; $B1
	db "LANA@@@@" ; $B2
	db "KIAWE@@@" ; $B3
	db "MALLOW@@" ; $B4
	db "SOPHCLS@" ; $B5
	db "ACEROLA@" ; $B6
	db "MINA@@@@" ; $B7
	db "HALA@@@@" ; $B8
	db "OLIVIA@@" ; $B9
	db "NANU@@@@" ; $BA
	db "HAPU@@@@" ; $BB
	db "KAHILI@@" ; $BC
	db "NOLAND@@" ; $BD
	db "GRETA@@@" ; $BE
	db "TUCKER@@" ; $BF
	db "LUCY@@@@" ; $C0
	db "SPENSER@" ; $C1
	db "BRANDON@" ; $C2
	db "ANABEL@@" ; $C3
	db "PALMER@@" ; $C4
	db "THORTON@" ; $C5
	db "DAHLIA@@" ; $C6
	db "DARACH@@" ; $C7
	db "ARGENTA@" ; $C8
	db "PROTON@@" ; $C9
	db "PETREL@@" ; $CA
	db "ARCHER@@" ; $CB
	db "ARIANA@@" ; $CC
	db "JESSIE@@" ; $CD
	db "JAMES@@@" ; $CE
	db "CASSIDY@" ; $CF
	db "BUTCH@@@" ; $D0
	db "BONNIE@@" ; $D1
	db "CLYDE@@@" ; $D2
	db "ATTILA@@" ; $D3
	db "HUN@@@@@" ; $D4
	db "DOMINO@@" ; $D5
	db "MIROR B@" ; $D6
	db "MATT@@@@" ; $D7
	db "SHELLY@@" ; $D8
	db "ARCHIE@@" ; $D9
	db "TABITHA@" ; $DA
	db "COURTNY@" ; $DB
	db "MAXIE@@@" ; $DC
	db "MARS@@@@" ; $DD
	db "JUPITER@" ; $DE
	db "SATURN@@" ; $DF
	db "CHARON@@" ; $E0
	db "CYRUS@@@" ; $E1
	db "N@@@@@@@" ; $E2
	db "COLRESS@" ; $E3
	db "GORM@@@@" ; $E4
	db "BRONIUS@" ; $E5
	db "ROOD@@@@" ; $E6
	db "ZINZOLN@" ; $E7
	db "GIALLO@@" ; $E8
	db "RYOKU@@@" ; $E9
	db "GHETSIS@" ; $EA
	db "ANTHEA@@" ; $EB
	db "CONCORD@" ; $EC
	db "ALIANA@@" ; $ED
	db "BRYONY@@" ; $EE
	db "CELOSIA@" ; $EF
	db "MABLE@@@" ; $F0
	db "XEROSIC@" ; $F1
	db "LYSANDR@" ; $F2
	db "TUPP@@@@" ; $F3
	db "ZIPP@@@@" ; $F4
	db "RAPP@@@@" ; $F5
	db "PLUMERA@" ; $F6
	db "GUZMA@@@" ; $F7
	db "FABA@@@@" ; $F8
	db "WICKE@@@" ; $F9
	db "LUSAMIN@" ; $FA
	db "CANDELA@" ; $FB
	db "BLANCHE@" ; $FC
	db "SPARK@@@" ; $FD
	db "SATOSHI@" ; $FE
	db "TAJIRI@@" ; $ff

WonderTradeOTNames2:
	db "SHIGERU@" ; $00
	db "HIBIKI@@" ; $01
	db "KOTONE@@" ; $02
	db "KAMON@@@" ; $03
	db "YUUKI@@@" ; $04
	db "HARUKA@@" ; $05
	db "MITSURU@" ; $06
	db "KOUKI@@@" ; $07
	db "HIKARI@@" ; $08
	db "JUN@@@@@" ; $09
	db "TOUYA@@@" ; $0A
	db "TOUKO@@@" ; $0B
	db "BEL@@@@@" ; $0C
	db "KYOUHEI@" ; $0D
	db "MEI@@@@@" ; $0E
	db "HELIOS@@" ; $0F
	db "SELENE@@" ; $10
	db "MIKE@@@@" ; $11
	db "KYLE@@@@" ; $12
	db "TIM@@@@@" ; $13
	db "EMY@@@@@" ; $14
	db "CHRIS@@@" ; $15
	db "KIM@@@@@" ; $16
	db "JACQUES@" ; $17
	db "HARI@@@@" ; $18
	db "JOY@@@@@" ; $19
	db "JENNY@@@" ; $1A
	db "DELIA@@@" ; $1B
	db "DAISY@@@" ; $1C
	db "FUJI@@@@" ; $1D
	db "BAOBA@@@" ; $1E
	db "COPYCAT@" ; $1F
	db "PRIMO@@@" ; $20
	db "LOSTELE@" ; $21
	db "TEALA@@@" ; $22
	db "SELPHY@@" ; $23
	db "JOEY@@@@" ; $24
	db "CAL@@@@@" ; $25
	db "CARRIE@@" ; $26
	db "MR.PKMN@" ; $27
	db "EUSINE@@" ; $28
	db "CAMERON@" ; $29
	db "EARL@@@@" ; $2A
	db "KURT@@@@" ; $2B
	db "BEN@@@@@" ; $2C
	db "MARY@@@@" ; $2D
	db "REED@@@@" ; $2E
	db "FERN@@@@" ; $2F
	db "LILY@@@@" ; $30
	db "BUENA@@@" ; $31
	db "RANDY@@@" ; $32
	db "MAXIMO@@" ; $33
	db "FELICTY@" ; $34
	db "MONICA@@" ; $35
	db "TUSCANY@" ; $36
	db "WESLEY@@" ; $37
	db "ARTHUR@@" ; $38
	db "FRIEDA@@" ; $39
	db "SANTOS@@" ; $3A
	db "SUNNY@@@" ; $3B
	db "NAOKO@@@" ; $3C
	db "SAYO@@@@" ; $3D
	db "ZUKI@@@@" ; $3E
	db "KUNI@@@@" ; $3F
	db "MIKI@@@@" ; $40
	db "LI@@@@@@" ; $41
	db "KIYO@@@@" ; $42
	db "SCOTT@@@" ; $43
	db "BRINEY@@" ; $44
	db "STONE@@@" ; $45
	db "WANDA@@@" ; $46
	db "GABBY@@@" ; $47
	db "TY@@@@@@" ; $48
	db "RYDEL@@@" ; $49
	db "STERN@@@" ; $4A
	db "AARUNE@@" ; $4B
	db "LISIA@@@" ; $4C
	db "ZINNIA@@" ; $4D
	db "INVER@@@" ; $4E
	db "CHAZ@@@@" ; $4F
	db "KIRI@@@@" ; $50
	db "JOHANNA@" ; $51
	db "LOOKER@@" ; $52
	db "CHERYL@@" ; $53
	db "RILEY@@@" ; $54
	db "BUCK@@@@" ; $55
	db "MARLEY@@" ; $56
	db "MIRA@@@@" ; $57
	db "ROSANNE@" ; $58
	db "JULIA@@@" ; $59
	db "JORDAN@@" ; $5A
	db "DEXTER@@" ; $5B
	db "KEIRA@@@" ; $5C
	db "FUEGO@@@" ; $5D
	db "HELENA@@" ; $5E
	db "HAWES@@@" ; $5F
	db "CHARLES@" ; $60
	db "CURTIS@@" ; $61
	db "YANCY@@@" ; $62
	db "INGO@@@@" ; $63
	db "EMMET@@@" ; $64
	db "GRACE@@@" ; $65
	db "ALEXA@@@" ; $66
	db "DEXIO@@@" ; $67
	db "SINA@@@@" ; $68
	db "GURKINN@" ; $69
	db "AZ@@@@@@" ; $6A
	db "EMMA@@@@" ; $6B
	db "PHIL@@@@" ; $6C
	db "NITA@@@@" ; $6D
	db "EVELYN@@" ; $6E
	db "DANA@@@@" ; $6F
	db "MORGAN@@" ; $70
	db "RYUKI@@@" ; $71
	db "GESTER@@" ; $72
	db "IMAKUNI@" ; $73
	db "RICHIE@@" ; $74
	db "ASSUNTA@" ; $75
	db "TRACEY@@" ; $76
	db "DUPLICA@" ; $77
	db "CASEY@@@" ; $78
	db "GISELLE@" ; $79
	db "MELANIE@" ; $7A
	db "DAMIAN@@" ; $7B
	db "ALAIN@@@" ; $7C
	db "REIKO@@@" ; $7D
	db "AYA@@@@@" ; $7E
	db "RAINER@@" ; $7F
	db "SPARKY@@" ; $80
	db "PYRO@@@@" ; $81
	db "MIKEY@@@" ; $82
	db "ORVILLE@" ; $83
	db "A.J.@@@@" ; $84
	db "CAMILA@@" ; $85
	db "A@@@@@@@" ; $86
	db "SLASH@@@" ; $87
	db "ALICE@@@" ; $88
	db "LEO@@@@@" ; $89
	db "AOOOO@@@" ; $8A
	db "JIMMY@@@" ; $8B
	db "CLY@@@@@" ; $8C
	db "LI'L D@@" ; $8D
	db "ARTY@@@@" ; $8E
	db "ABE@@@@@" ; $8F
	db "BABA@@@@" ; $90
	db "EVAN@@@@" ; $91
	db "PAUL@@@@" ; $92
	db "CYAN@@@@" ; $93
	db "REVO@@@@" ; $94
	db "EVERYLE@" ; $95
	db "ZETSU@@@" ; $96
	db "KARUTA@@" ; $97
	db "NOZOMI@@" ; $98
	db "AMOS@@@@" ; $99
	db "KAITO@@@" ; $9A
	db "MEIKO@@@" ; $9B
	db "MIKU@@@@" ; $9C
	db "RIN@@@@@" ; $9D
	db "LEN@@@@@" ; $9E
	db "LUKA@@@@" ; $9F
	db "TETO@@@@" ; $A0
	db "AMI@@@@@" ; $A1
	db "MINAKO@@" ; $A2
	db "USAGI@@@" ; $A3
	db "REI@@@@@" ; $A4
	db "MAKOTO@@" ; $A5
	db "MAMORU@@" ; $A6
	db "LUNA@@@@" ; $A7
	db "ARTEMIS@" ; $A8
	db "DIANA@@@" ; $A9
	db "SAKURA@@" ; $AA
	db "TOMOYO@@" ; $AB
	db "SYAORAN@" ; $AC
	db "SHINJI@@" ; $AD
	db "ASUKA@@@" ; $AE
	db "MARI@@@@" ; $AF
	db "GENDO@@@" ; $B0
	db "YUI@@@@@" ; $B1
	db "KAWORU@@" ; $B2
	db "OKABE@@@" ; $B3
	db "DARU@@@@" ; $B4
	db "KURISU@@" ; $B5
	db "SUZUHA@@" ; $B6
	db "MAYURI@@" ; $B7
	db "RUKA@@@@" ; $B8
	db "KYON@@@@" ; $B9
	db "HARUHI@@" ; $BA
	db "YUKI@@@@" ; $BB
	db "MIKURU@@" ; $BC
	db "TSURUYA@" ; $BD
	db "RYOKO@@@" ; $BE
	db "ITSUKI@@" ; $BF
	db "JOJO@@@@" ; $C0
	db "JOTARO@@" ; $C1
	db "JOSUKE@@" ; $C2
	db "DIO@@@@@" ; $C3
	db "KEI@@@@@" ; $C4
	db "SAIKA@@@" ; $C5
	db "HAYATE@@" ; $C6
	db "DARUKU@@" ; $C7
	db "NAGISA@@" ; $C8
	db "BRIDGET@" ; $C9
	db "RYO@@@@@" ; $CA
	db "CLARA@@@" ; $CB
	db "HANA@@@@" ; $CC
	db "MIYUKI@@" ; $CD
	db "LUKE@@@@" ; $CE
	db "VULPES@@" ; $CF
	db "BENNY@@@" ; $D0
	db "SARAH@@@" ; $D1
	db "R.HOUSE@" ; $D2
	db "VICTOR@@" ; $D3
	db "SUNNY@@@" ; $D4
	db "CASS@@@@" ; $D5
	db "BOONE@@@" ; $D6
	db "FELICIA@" ; $D7
	db "ARCADE@@" ; $D8
	db "RINGO@@@" ; $D9
	db "PETE@@@@" ; $DA
	db "TORRES@@" ; $DB
	db "JACKSON@" ; $DC
	db "RANGI@@@" ; $DD
	db "REMY@@@@" ; $DE
	db "SYLVIE@@" ; $DF
	db "MATTHEW@" ; $E0
	db "MATEO@@@" ; $E1
	db "BABS@@@@" ; $E2
	db "PIA@@@@@" ; $E3
	db "AIZAWA@@" ; $E4
	db "SUKI@@@@" ; $E5
	db "FREDRIK@" ; $E6
	db "DRAYANO@" ; $E7
	db "HLIN@@@@" ; $E8
	db "MARCKUS@" ; $E9
	db "PUM@@@@@" ; $EA
	db "BRYAN@@@" ; $EB
	db "DON@@@@@" ; $EC
	db "MIGUEL@@" ; $ED
	db "SATORU@@" ; $EE
	db "IWATA@@@" ; $EF
	db "JUNICHI@" ; $F0
	db "MASUDA@@" ; $F1
	db "KOJI@@@@" ; $F2
	db "NISHINO@" ; $F3
	db "SOSUKE@@" ; $F4
	db "TAMADA@@" ; $F5
	db "HISASHI@" ; $F6
	db "SOGABE@@" ; $F7
	db "KEITA@@@" ; $F8
	db "KAGAYA@@" ; $F9
	db "YOSHI@@@" ; $FA
	db "MATSUDA@" ; $FB
	db "SHIGEKI@" ; $FC
	db "TETSUYA@" ; $FD
	db "OOTA@@@@" ; $FE
	db "TURNER@@" ; $FF
